#!/usr/bin/env python3
"""One-shot: writes scripts/prd-question-triage.json (the 2026-09-20 gap-closure
triage of docs/37's open questions — who can answer each one).

Buckets are stakeholder-owned EXCEPT the last one ("Internal — Tech-Lead can
decide now"), whose rows carry a proposed answer marked
'Proposed — pending sign-off' (the proposal adopts the PRD's own
'Recommended:' text where present, or the binding spec where it already
decided the point; sign-off is still the owner's to give).

Re-running is idempotent. Do not edit the JSON by hand — edit this file.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent

BUCKETS = [
    "FunderBlu COO",
    "FunderBlu Risk Owner",
    "FunderBlu Ops Owner",
    "FunderBlu Product Owner",
    "FunderBlu Marketing",
    "FunderBlu Legal",
    "FunderBlu CEO",
    "Broker (Shadab)",
    "Sales (unassigned)",
    "External vendors (Veriff / payment rails)",
    "Internal — Tech-Lead can decide now",
]
INT = BUCKETS[-1]

# (section, question, bucket, note)
ROWS = [
 # ---------------- DevOps & Deployment ----------------
 ("DevOps & Deployment",
  "What trigger moves us from Compose to Kubernetes: service count, tenant count, or multi-region? Recommended: none of these in year one.",
  INT,
  "Proposed — pending sign-off: adopt 'none of these in year one'. docs/06 §11 keeps K8s forbidden, revisited only at > 50 tenants or multi-region."),
 ("DevOps & Deployment",
  "Backup retention period and off-host copy destination, for example a Hetzner Storage Box?",
  INT,
  "Proposed — pending sign-off: the 3-2-1 scheme is already binding (D55, docs/06 §2.4) — prod box + standby host + off-provider object store (B2/Wasabi, object lock, separate credentials); retention is tool-managed by pgBackRest, exact day-counts fixed at the freeze session."),
 ("DevOps & Deployment",
  "On-call rotation and alert channel for a 4 to 5 person team: which Telegram group or phone tree?",
  "FunderBlu Ops Owner",
  "Staffing decision: who is paged. The alert *set* is already defined (docs/06 §2.7/D76: CRITICAL pages), the roster is not."),
 ("DevOps & Deployment",
  "Staging data: synthetic only, or anonymized production copies, and what are the anonymization rules?",
  INT,
  "Proposed — pending sign-off: synthetic only — no production PII ever lands in staging (docs/28 PII posture; consistent with the companion row 'synthetic-only approved')."),
 ("DevOps & Deployment",
  "Do we need a bastion or VPN for production access in V1, or is keyed SSH with fail2ban sufficient?",
  INT,
  "Proposed — pending sign-off: keyed SSH + UFW + fail2ban + Cloudflare origin-auth in V1 (docs/28 §3.1); bastion is a V2 item."),
 ("DevOps & Deployment",
  "What RPO and RTO does the business accept, for example RPO 15 minutes and RTO 4 hours?",
  "FunderBlu COO",
  "Business-acceptance question. The spec has already committed to RPO ≤ 5 min (pgBackRest, D55) and RTO ≤ 15 min promoted / ≤ 2 h worst case (D56, docs/06 §2.4) — COO confirms the business accepts those numbers; rejecting them overturns D55/D56, it is not a retune."),
 ("DevOps & Deployment",
  "PgBouncer in front of Postgres or application-level pooling only? Recommended: PgBouncer.",
  INT,
  "Proposed — pending sign-off: PgBouncer — already a V1 deployable (`db-proxy`, docs/01 §1.1)."),
 ("DevOps & Deployment",
  "V1 database strategy: single instance with rehearsed restore inside RTO, or warm standby from day one? Recommended: single instance plus drills.",
  INT,
  "Proposed — pending sign-off: as documented post-D56 — prod single box (accepted SPOF, ADR-9/10) PLUS the D56 warm standby (disaster replica, promote ≤ 15 min, docs/06 §2.4/§11). The PRD's 'single plus drills' predates D55/D56 and is superseded by them."),
 ("DevOps & Deployment",
  "What are the load test target numbers: concurrent trader sessions, sync batch size, payout burst volume?",
  INT,
  "Proposed — pending sign-off: adopt the docs/29 capacity model — sync throughput per the docs/08 §11 rows (431 accounts ≈ 7.2 req/s; 5k accounts ≈ 83 req/s), load test at 10× V1 targets (docs/06 blueprint step 10, OPS-29 k6 scripts)."),
 ("DevOps & Deployment",
  "Is synthetic-only staging data approved, meaning no production PII ever lands in staging? Recommended: yes.",
  INT,
  "Proposed — pending sign-off: yes — docs/28 PII posture (no production PII in non-prod environments)."),

 # ---------------- Trading Platform Bridge ----------------
 ("Trading Platform Bridge",
  "MetaApi or Brokeree for MT5? Decision criteria: provisioning API coverage, price per account, sandbox quality, support response.",
  INT,
  "Proposed — pending sign-off: MetaApi — it is the binding V1 choice (docs/01 §1.1 `bridge` row; the entire docs/08 design; docs/00 'MT5 via MetaApi in V1'). Brokeree comparison stays a V2 vendor-review input (see the pricing row)."),
 ("Trading Platform Bridge",
  "Does the broker contract grant API rights for account creation, disable, enable, close all, group assignment, and password reset, or are some manual in broker manager? If manual, enforcement and provisioning designs degrade.",
  "Broker (Shadab)",
  "Only the broker can answer. Every 'manual' item forces a human step into BRG-05/10/11 — get the API-rights list in writing before contract freeze."),
 ("Trading Platform Bridge",
  "What is the default sync interval per tenant and the minimum safe interval given vendor rate limits?",
  INT,
  "Proposed — pending sign-off: per-account `poll_interval_s` default 60 (docs/32 `broker_accounts.poll_interval_s`); the interval widens ×2 automatically when p95 > 2 s and MetaApi rate limits are the binding constraint (docs/08 §3/§11)."),
 ("Trading Platform Bridge",
  "Daily drawdown reset follows broker server time or a tenant-configured timezone?",
  "FunderBlu Risk Owner",
  "Risk semantics — the reset instant defines 'daily drawdown'. (Same question raised under Evaluation Engine.)"),
 ("Trading Platform Bridge",
  "Which MT5 groups map to which phases, and who creates those groups at the broker, broker ops or API?",
  "Broker (Shadab)",
  "Broker-side topology + who operates it."),
 ("Trading Platform Bridge",
  "Do we store trader terminal passwords in our database or delegate password generation and delivery to the vendor? Needs a security review.",
  INT,
  "Proposed — pending sign-off: store platform-side, field-encrypted AES-256-GCM with key versioning (BRG-44; docs/32 `broker_accounts.credentials_enc`/`cred_key_version`). The security review at freeze verifies key handling — the storage decision itself is already made in the DDL."),
 ("Trading Platform Bridge",
  "If the broker does not offer MatchTrader, is cTrader the fallback second platform for V1?",
  "Broker (Shadab)",
  "Depends on broker platform support; the platform is MetaTrader 5 in V1 (docs/00/01)."),
 ("Trading Platform Bridge",
  "Can broker groups be created by API, or does broker ops create them manually per request?",
  "Broker (Shadab)",
  "Broker capability — same family as the API-rights row; 'manual' means a human step in provisioning."),
 ("Trading Platform Bridge",
  "Default sync interval per account phase: same interval for evaluation and funded, or faster for funded?",
  "FunderBlu Risk Owner",
  "Risk posture for funded accounts (more money at risk → tighter monitoring is the risk question, not an engineering one)."),
 ("Trading Platform Bridge",
  "Investor password: delivered by default in the credential email or only on request?",
  "FunderBlu Ops Owner",
  "Credential-delivery policy (same family as the lifecycle 'delivery channels' row)."),
 ("Trading Platform Bridge",
  "Enforcement retry policy: max attempts, backoff ceiling, and escalation SLA for ops response.",
  INT,
  "Proposed — pending sign-off: as designed in docs/08 — commands run `pending → executing → confirmed | failed(retry) → dead`; reconnect retries 3 with 30 s halving backoff; a dead enforcement command never auto-retries past dead → CON CRITICAL + human (the escalation SLA is the on-call response time in the docs/06 runbooks)."),
 ("Trading Platform Bridge",
  "At what active account count does MetaApi per- account pricing become more expensive than Brokeree or self-hosted alternatives?",
  "Broker (Shadab)",
  "Vendor pricing data — a commercial input for the year-2 vendor review, not a V1 design input."),
 ("Trading Platform Bridge",
  "Maximum tolerable sync outage before we alert traders or pause provisioning?",
  "FunderBlu Risk Owner",
  "Risk tolerance question (raised with the Risk Owner in the PRD)."),

 # ---------------- KYC / Verification ----------------
 ("KYC / Verification",
  "Does FunderBlu's Veriff contract include webhook endpoints or only polling? This affects KYC-05 implementation.",
  "External vendors (Veriff / payment rails)",
  "Contract fact only Veriff can confirm; the platform handles both (webhook + poll fallback, docs/13)."),
 ("KYC / Verification",
  "What KYC verification level does each FunderBlu challenge type require at migration? Map each challenge to basic, enhanced, or skipped.",
  "FunderBlu Legal",
  "Compliance-level mapping per product — determines KYC-07/08 gates at cutover."),
 ("KYC / Verification",
  "Do we require proof of address in V1 or only ID plus liveness as Veriff defaults?",
  "FunderBlu Legal",
  "KYC policy (jurisdiction-driven)."),
 ("KYC / Verification",
  "What is the restricted country list for V1, and does it apply at registration, at KYC, or both?",
  "FunderBlu Legal",
  "Jurisdiction policy; the enforcement points (registration gate + KYC-13) exist in the spec, the list does not."),
 ("KYC / Verification",
  "Which role can approve KYC manually in the fallback path, and does it require dual control?",
  "FunderBlu Ops Owner",
  "Role + control decision (the KYC-11 manual path is V1.1)."),
 ("KYC / Verification",
  "How many resubmission attempts are allowed before final rejection?",
  "FunderBlu Legal",
  "KYC policy (same family as the 'before contact support' row)."),
 ("KYC / Verification",
  "Do we store only Veriff media references, or also cache documents in our object storage for manual cases? Recommended: manual cases only.",
  "FunderBlu Legal",
  "Data-retention choice. PRD recommends 'manual cases only' — consistent with the docs/13 §5 R2 retention posture; sign-off needed."),
 ("KYC / Verification",
  "What is the KYC document retention period required by FunderBlu's jurisdiction? This determines KYC-31 configuration.",
  "FunderBlu Legal",
  "Jurisdiction retention law."),
 ("KYC / Verification",
  "Does FunderBlu require proof of address for all challenges or only funded accounts? This affects KYC- 28 configuration.",
  "FunderBlu Legal",
  "KYC policy (funded = higher level is the usual answer; Legal confirms)."),
 ("KYC / Verification",
  "What is the acceptable SLA for manual KYC review? Current target is 4 hours but confirm with operations.",
  "FunderBlu Ops Owner",
  "Staffing/SLA confirmation — the 4 h target is theirs to confirm."),
 ("KYC / Verification",
  "Do we need KYC re-verification on an annual cycle or only on document expiry?",
  "FunderBlu Legal",
  "Compliance cycle (V2 machinery, KYC-21/25 — the answer sets scope)."),
 ("KYC / Verification",
  "What happens to KYC data when a trader account is terminated? Immediate deletion, retention period, or anonymization?",
  "FunderBlu Legal",
  "PII end-of-life policy."),
 ("KYC / Verification",
  "Does FunderBlu require selfie/liveness for all KYC levels or only enhanced? This affects Veriff configuration.",
  "FunderBlu Legal",
  "KYC level policy (Veriff configuration follows)."),
 ("KYC / Verification",
  "What is the maximum number of KYC resubmission attempts before the trader must contact support?",
  "FunderBlu Legal",
  "KYC policy (twin of the 'before final rejection' row — both need one number)."),
 ("KYC / Verification",
  "Do we need to support KYC for traders who registered before the KYC module was live (migration backfill)?",
  "FunderBlu Ops Owner",
  "Migration-scope decision (who gets re-verified, when)."),

 # ---------------- Analytics & BI ----------------
 ("Analytics & BI",
  "Confirm the exact V1 report list against the reports FunderBlu uses today in TTS: which of the eleven risk tabs map into V1?",
  "FunderBlu Product Owner",
  "Product scope — which TTS reports are V1-mandatory."),
 ("Analytics & BI",
  "What timezone defines the daily and monthly cutoff for aggregates: tenant timezone or UTC?",
  "FunderBlu Product Owner",
  "Business-reporting semantics (same family as the 'reporting day boundary' row — one answer covers both)."),
 ("Analytics & BI",
  "Do we expose a report API to tenants for their own BI tools in V1? Recommended: no, CSV export only.",
  "FunderBlu Product Owner",
  "Scope call. PRD recommends CSV-only — matches the V1 surface (ANA-32 exports); the report API is a V2 candidate."),
 ("Analytics & BI",
  "What is the read model rebuild procedure if a read model corrupts: full replay from the event log, and how long must that take?",
  INT,
  "Proposed — pending sign-off: full replay from the 13-month event log (docs/19 ANA-14 pattern); time budget at V1 scale to be fixed at the freeze — proposed target < 1 h, measured in the exit test."),
 ("Analytics & BI",
  "Which roles receive financial reports by default, and does the support role see any analytics at all?",
  "FunderBlu Ops Owner",
  "Role/permission policy — who holds which reports."),
 ("Analytics & BI",
  "Which of TTS's report tabs must be reproduced at cutover, and which can wait? This gates cutover.",
  "FunderBlu Product Owner",
  "Cutover gate — Product owns the must-have list."),
 ("Analytics & BI",
  "What is the business definition of an active account and a pass? These definitions must be pinned before any KPI is trusted.",
  "FunderBlu Product Owner",
  "Business definitions — the spec can only compute what the business defines."),
 ("Analytics & BI",
  "Is reporting day boundary in tenant timezone or UTC?",
  "FunderBlu Product Owner",
  "Twin of the 'cutoff timezone' row — one answer."),
 ("Analytics & BI",
  "Is nightly batch freshness acceptable for all reports, or do any reports need near-real-time?",
  "FunderBlu Product Owner",
  "Freshness expectation per report (V1 default: nightly batch; near-real-time list = scope addition)."),
 ("Analytics & BI",
  "How far back must trend data be retained for trend views?",
  INT,
  "Proposed — pending sign-off: 13 months — matches the event log retention the read models replay from (docs/19: 'retention 13 months (matches the events log, 04)'. Longer trends need the R2 archive, a V2 item)."),

 # ---------------- Support Inbox ----------------
 ("Support Inbox",
  "Does FunderBlu want the support inbox in the first cutover, or can Telegram/email remain primary until Phase 4?",
  "FunderBlu COO",
  "Cutover-scope decision (the inbox is Phase-4 content in docs/99 — the question is whether FunderBlu waits)."),
 ("Support Inbox",
  "What are the V1 support categories: account, payout, KYC, payment, breach, technical, general, or a different list?",
  "FunderBlu Ops Owner",
  "Support-ops taxonomy — the team that staffs it defines the buckets."),
 ("Support Inbox",
  "What are the SLA targets per priority, for example urgent first response within 1 hour and normal within 24 hours?",
  "FunderBlu Ops Owner",
  "SLA targets — an ops-commitment, not an engineering number."),
 ("Support Inbox",
  "Are traders allowed to appeal breaches through support tickets, and who can make final decisions on appeals?",
  "FunderBlu Risk Owner",
  "Appeal authority is a risk decision (ties to the EVL-20 override record, docs/07 §3.2)."),
 ("Support Inbox",
  "What file types and size limits are allowed for attachments? Recommended: images and PDFs only, max 10 MB per file.",
  INT,
  "Proposed — pending sign-off: adopt the PRD recommendation — images + PDFs only, 10 MB per file (docs/40 uploads-coverage limits)."),
 ("Support Inbox",
  "Does Telegram intake mean full two-way sync in V1, or only linking Telegram messages manually to a ticket? Recommended: defer full sync.",
  INT,
  "Proposed — pending sign-off: defer full sync — manual linking only in V1 (Telegram is a V2 platform channel anyway, docs/14; the CHT Discord/Telegram relay is Phase 4, docs/99 4.1)."),
 ("Support Inbox",
  "Should support staff be allowed to see payout destination details inside tickets, or should these remain masked unless the staff role has finance permission?",
  "FunderBlu COO",
  "Sensitive-data visibility policy (payout destinations = financial PII)."),
 ("Support Inbox",
  "Do resolved tickets auto-close after a fixed period, and what is the default duration?",
  INT,
  "Proposed — pending sign-off: auto-close resolved tickets after 7 days (proposed default — ops-visible, trivially tunable per tenant later)."),

 # ---------------- Evaluation Engine ----------------
 ("Evaluation Engine",
  "Daily drawdown reset follows broker server midnight or a tenant-configured reset time?",
  "FunderBlu Risk Owner",
  "Risk semantics — the reset instant defines 'daily drawdown' (same question as the Bridge row; one answer for both)."),
 ("Evaluation Engine",
  "What is the default basis, equity or balance, for daily and max drawdown across FunderBlu products?",
  "FunderBlu Risk Owner",
  "Risk semantics per product — drives the rule-pack defaults."),
 ("Evaluation Engine",
  "Which rules are hard breach versus soft breach by default in V1 product configs?",
  "FunderBlu Risk Owner",
  "Risk policy — hard breach = immediate disable+close (EVL-17 path); the default per rule is a risk call."),
 ("Evaluation Engine",
  "Does auto-pass apply to the final evaluation phase or does live verification always require manual review, as TTS defaulted?",
  "FunderBlu Risk Owner",
  "Risk process — manual review at the funded boundary is the conservative TTS default; Risk Owner decides."),
 ("Evaluation Engine",
  "Is the consistency rule evaluated only at payout request or continuously on funded accounts?",
  "FunderBlu Risk Owner",
  "Risk-monitoring scope (raised with the Risk Owner). Continuous = more enforcement commands; request-time = cheaper but slower."),
 ("Evaluation Engine",
  "News calendar source in V1: manually maintained internal calendar or an external feed provider?",
  "FunderBlu Risk Owner",
  "Risk-data input for the news-trading rule — a vendor + cost + reliability call owned by Risk."),
 ("Evaluation Engine",
  "Do we support per-instrument rule sets in V1 or only global per-phase rules plus restricted symbol flags? Expected: global only.",
  "FunderBlu Risk Owner",
  "Rule-semantics scope. PRD expects global-only — Risk Owner confirms the rule-pack model stays simple for V1."),

 # ---------------- Account Lifecycle ----------------
 ("Account Lifecycle",
  "Is AWAITING_ACTIVATION a separate state or a flag on PASS_PENDING? Separate state recommended for clarity.",
  INT,
  "Proposed — pending sign-off: separate state — it is already a state in the binding LCC-02 machine (docs/07 §3.1 state diagram)."),
 ("Account Lifecycle",
  "Which challenges get free retakes, how many, and is that configured per challenge or per tenant?",
  "FunderBlu COO",
  "Commercial policy — retakes are a give-away with real cost."),
 ("Account Lifecycle",
  "On suspension with open positions: disable trading only, or close positions as well?",
  "FunderBlu Risk Owner",
  "Risk posture on suspended accounts (disable = LCC-11 V1.1; close-positions adds the BRG-10 path)."),
 ("Account Lifecycle",
  "How long do terminal accounts stay hot before archive, for example 12 months?",
  INT,
  "Proposed — pending sign-off: 12 months hot, then archive — sits inside the 13-month event-log window so replays still resolve them (LCC-27 cleanup, docs/07 §5)."),
 ("Account Lifecycle",
  "Which TTS account states map to which new states, and do imported accounts keep original rule versions or bind to new versions?",
  "FunderBlu Ops Owner",
  "Migration plan (docs/25 cutover) — the mapping table is an ops artifact with risk sign-off."),
 ("Account Lifecycle",
  "Do giveaway and partner accounts skip payout eligibility rules or use custom payout terms?",
  "FunderBlu COO",
  "Commercial policy — non-commercial accounts and the payout gate."),
 ("Account Lifecycle",
  "Credential delivery channels: portal only, email only, or both, and do we issue a read-only investor password?",
  "FunderBlu Ops Owner",
  "Delivery policy (raised with the Ops Owner); the read-only investor password already exists in the spec (BRG-06/44)."),

 # ---------------- Checkout & Billing ----------------
 ("Checkout & Billing",
  "Which providers are confirmed for V1 launch: Match2Pay, Interkasa, and which crypto rail exactly?",
  "External vendors (Veriff / payment rails)",
  "Provider confirmations (the spec assumes Match2Pay + Interkasa + NOWPayments — docs/12 §1; the crypto network list is the open part)."),
 ("Checkout & Billing",
  "During migration parallel run, does FunderBlu keep its current external checkout and cut over per cohort, or switch all at once?",
  "FunderBlu COO",
  "Cutover strategy (docs/25 parallel run) — a business-continuity call."),
 ("Checkout & Billing",
  "Coupon stacking rules: one coupon per order, and can affiliate coupons combine with promo coupons?",
  "FunderBlu COO",
  "Commercial policy (affiliates are deferred, so the combining half is a V2 input)."),
 ("Checkout & Billing",
  "Final V1 add-on list: reset, swap-free, and time extension only, or more?",
  "FunderBlu Product Owner",
  "Product scope — the add-on set at launch."),
 ("Checkout & Billing",
  "Refund policy window and approval role: COO only or a finance role as well?",
  "FunderBlu COO",
  "Money-control policy (the refund state machine exists, docs/12 §3.4; the window + role are the policy)."),
 ("Checkout & Billing",
  "Login-first checkout or guest checkout with quick signup? Recommended: login-first with fast signup.",
  "FunderBlu Product Owner",
  "UX scope call. PRD recommends login-first — the spec already builds login-first (docs/12 §1 'Login-first checkout')."),
 ("Checkout & Billing",
  "How many network confirmations for crypto payments before provisioning starts?",
  "External vendors (Veriff / payment rails)",
  "Rail-provider confirmation counts (NOWPayments); sets the fraud window before provisioning starts."),

 # ---------------- Payout System ----------------
 ("Payout System",
  "Which payout rails and networks are confirmed for V1: which crypto networks such as TRC20 or ERC20, and which fiat rail?",
  "External vendors (Veriff / payment rails)",
  "NOWPayments network support + the fiat rail choice."),
 ("Payout System",
  "Are partial payouts allowed by default across FunderBlu products, and what are the min and max thresholds per challenge?",
  "FunderBlu COO",
  "Payout policy per product (the mechanics — PAY-02 available-profit formula — are spec'd; the policy values are not)."),
 ("Payout System",
  "Is auto-approve ever enabled in V1 or is approval manual only at launch? Recommended: manual at launch.",
  "FunderBlu COO",
  "Money-approval policy. Spec posture: manual-only at launch (docs/11 — the API request path is always-manual); COO confirms."),
 ("Payout System",
  "What is the second approval threshold amount for V1?",
  "FunderBlu COO",
  "Money-control threshold."),
 ("Payout System",
  "Post-payout balance handling: keep the remainder or reset to initial after a full payout?",
  "FunderBlu Product Owner",
  "Product mechanics — the HWM-based available-profit formula (docs/11 §3.2) works either way; the product decision is what 'full payout' means for the account."),
 ("Payout System",
  "What are the payout frequency defaults per product: bi- weekly, monthly, or on-demand?",
  "FunderBlu COO",
  "Payout policy per product (funded terms: `payout_frequency`, docs/11 §3.2 — the values are the policy)."),
 ("Payout System",
  "Do affiliate commissions flow through this payout engine in V1? Expected: no, affiliate module is deferred.",
  INT,
  "Proposed — pending sign-off: no — the affiliate module is deferred (docs/23; out-of-scope register docs/38), so the V1 payout engine pays trader payouts only. Revisit when AFF lands."),

 # ---------------- Notification Service ----------------
 ("Notification Service",
  "Who designs and provides the HTML/CSS for the 10 core email templates?",
  "FunderBlu Marketing",
  "Design ownership — the platform ships the NOT-01 engine + the D61 closed template set (docs/14), the brand work is Marketing's."),
 ("Notification Service",
  "Do we need SMS notifications in V1? Recommended: no, email and in-app only.",
  "FunderBlu Product Owner",
  "Scope call. Spec posture already excludes SMS from V1 (docs/14: email in V1; in-app + Telegram in V2)."),
 ("Notification Service",
  "How do we handle email bounces: suppress immediately, or allow manual override by support?",
  "FunderBlu Ops Owner",
  "Support/ops procedure (suppression list ownership)."),
 ("Notification Service",
  "Telegram bot hosting: run as a separate worker in our Hetzner stack or use a managed bot service? Recommended: separate worker.",
  INT,
  "Proposed — pending sign-off: no V1 decision needed — Telegram is a V2 channel (docs/14). When it lands: separate worker, per the PRD recommendation (it would run inside the `workers` deployable)."),
 ("Notification Service",
  "Do broadcasts respect user notification preferences, or do they override them for critical system announcements?",
  "FunderBlu Product Owner",
  "Product policy — critical-announcement override vs preference respect."),

 # ---------------- Document Generation ----------------
 ("Document Generation",
  "Do we need a visual drag-and-drop template designer in V1? Recommended: No, use hardcoded templates with JSON config for variables.",
  "FunderBlu Product Owner",
  "Scope call. PRD recommends hardcoded + JSON config — matches docs/15 (DOC-01 templates with vars)."),
 ("Document Generation",
  "What are the exact V1 certificate types? Recommended: Challenge Passed, Funded Trader, Payout Receipt.",
  "FunderBlu Product Owner",
  "Product scope. PRD's recommendation matches the D61 set (docs/14: phase_passed, funded certificate via DOC-04)."),
 ("Document Generation",
  "Do we need a QR code on the certificate for external verification in V1? Recommended: No, unique ID is enough for V1.",
  INT,
  "Proposed — pending sign-off: no QR — verification is the unique certificate hash via the /v1/documents/verify endpoint (docs/15; the D61 set ships hash-verification, not QR)."),

 # ---------------- Trader Dashboard ----------------
 ("Trader Dashboard",
  "What is the default polling interval for dashboard data: 30 seconds or 60 seconds?",
  INT,
  "Proposed — pending sign-off: SSE islands are the primary path with the TD-11 fallback (1/2/5/15 s backoff, docs/16 §3); default poll 30 s for live trading views, 60 s for static views (proposed default — the spec leaves the interval open)."),
 ("Trader Dashboard",
  "Does the trader portal include marketing and pricing pages in V1, or does the tenant's external website handle marketing and link into checkout? Recommended: external site links in.",
  "FunderBlu Product Owner",
  "Scope call. PRD recommends external site — consistent with CMS being V2 (docs/01 phase 3)."),
 ("Trader Dashboard",
  "Single theme per tenant or a user-toggleable dark and light mode in V1? Recommended: tenant theme only.",
  "FunderBlu Product Owner",
  "Scope call. PRD recommends tenant theme only."),
 ("Trader Dashboard",
  "What columns and row limits apply to trade history CSV export?",
  INT,
  "Proposed — pending sign-off: columns = the TD trade table (ticket, symbol, side, volume, open/close price & time, profit); row limit 10,000 (proposed default — export is a docs/16 TD surface; the limit is tunable per tenant later)."),
 ("Trader Dashboard",
  "Which terminology strings does FunderBlu want customized at launch, for example challenge versus evaluation?",
  "FunderBlu Product Owner",
  "Branding content — the terminology map mechanism exists (TEN); the string list is FunderBlu's."),

 # ---------------- Admin Panel ----------------
 ("Admin Panel",
  "Which default roles ship in V1, for example admin, finance, risk, support, and marketing, and what permission subsets do they carry?",
  "FunderBlu Ops Owner",
  "Role model — the permission *framework* is spec'd (roles.yaml, docs/02/46); which roles + subsets ship is the staffing call."),
 ("Admin Panel",
  "Does the account detail include device activity and IP events in V1, or only after the risk detectors land in Phase 4?",
  "FunderBlu Product Owner",
  "Scope call — V1 risk surface vs Phase-4 detectors."),
 ("Admin Panel",
  "Which reports map to the first read models: daily, monthly financial, challenge versus payout, country payout, top earners?",
  "FunderBlu Product Owner",
  "Report scope (pairs with the Analytics report-list rows)."),
 ("Admin Panel",
  "Confirm masking policy: no staff role can view raw trader trading passwords, only trigger a resend.",
  "FunderBlu Ops Owner",
  "Security-policy confirmation — the spec already implements 'resend-only' (BRG-13/17 V2, no raw reveal in V1); Ops confirms the policy for the role matrix."),
 ("Admin Panel",
  "Email template editor in V1: text and variables only with locked layout, or full HTML? Recommended: text and variables only.",
  "FunderBlu Product Owner",
  "Scope call. PRD recommends text + variables — matches the NOT-01 template model (docs/14)."),
 ("Admin Panel",
  "Bulk operation guardrails: maximum selection size and mandatory confirmation step?",
  INT,
  "Proposed — pending sign-off: max selection 500 per bulk operation + mandatory confirmation step (proposed default — the bulk endpoints don't exist yet, the guardrail ships with them, ADM-05 surface)."),

 # ---------------- Risk Management ----------------
 ("Risk Management",
  "Confirm the V1 detector set: IP overlap, device overlap, copy, inverse, and KYC reuse in V1, with payment reuse at P2.",
  "FunderBlu Risk Owner",
  "Detector scope confirmation (raised with the Risk Owner)."),
 ("Risk Management",
  "What open and close time delta and symbol match window counts as correlated for the copy detector in V1?",
  "FunderBlu Risk Owner",
  "Detector threshold — a risk-tuning number, not an engineering one."),
 ("Risk Management",
  "What score thresholds auto-open a case per signal type, versus info-only signals?",
  "FunderBlu Risk Owner",
  "Auto-open thresholds (the case model + D71 one-open-case rule are spec'd; the scores are risk's)."),
 ("Risk Management",
  "Does an open case block new challenge purchases as well as payouts? Recommended: payouts only in V1.",
  "FunderBlu Risk Owner",
  "Risk policy. PRD recommends payouts-only — the spec's hold interlock (PAY-04/RSK-11, D68) covers payouts; purchase-blocking would be a new gate."),
 ("Risk Management",
  "Device fingerprinting in V1: ipinfo flags only, or add FingerprintJS now? Recommended: ipinfo now, FingerprintJS when volume justifies cost.",
  INT,
  "Proposed — pending sign-off: adopt 'ipinfo now' — the cost gate is a volume decision; the signal schema already carries device flags (docs/10 RSK signals)."),
 ("Risk Management",
  "Who owns the risk staff role definition and the case review SLA, for example review within 24 hours?",
  "FunderBlu Risk Owner",
  "Risk-ops ownership (role definition + SLA)."),
 ("Risk Management",
  "What is the retention period for signals and device logs?",
  "FunderBlu Legal",
  "Retention policy for surveillance data (sensitive PII-adjacent)."),

 # ---------------- Affiliate System ----------------
 ("Affiliate System",
  "Does FunderBlu migrate its existing affiliate program at cutover, or keep it running externally until Phase 4 lands? This changes the migration plan.",
  "FunderBlu COO",
  "Migration-scope decision (the module is deferred — docs/23/38 — so 'keep external' is the default until Phase 4)."),
 ("Affiliate System",
  "Commission basis in V1: first order only, or every order from a referred trader?",
  "FunderBlu COO",
  "Commercial policy (V2 module, but the answer shapes the migration data model)."),
 ("Affiliate System",
  "What refund window length gates commission approval, for example 14 days?",
  "FunderBlu COO",
  "Commercial policy."),
 ("Affiliate System",
  "What is the minimum payout threshold and which payout rails do affiliates use, same as traders or separate?",
  "FunderBlu COO",
  "Commercial policy."),
 ("Affiliate System",
  "Does FunderBlu's current program use tiered or multi- tier commissions? If yes, V1 scope must change.",
  "FunderBlu COO",
  "Fact about the current program — a 'yes' is a scope change to the deferred module."),
 ("Affiliate System",
  "What cookie duration applies by default, for example 30 days?",
  "FunderBlu Marketing",
  "Attribution-window policy (marketing owns referral attribution)."),
 ("Affiliate System",
  "Can a trader also be an affiliate, and is self-purchase through own link blocked outright or flagged for review?",
  "FunderBlu COO",
  "Program policy (self-referral = the fraud-adjacent edge; the spec's aff.self_referral block exists, the policy is COO's)."),

 # ---------------- CRM & Communications ----------------
 ("CRM & Communications",
  "Which automated sequences are must-have at launch for FunderBlu: welcome, cart abandonment, retry reminder, or re-engagement?",
  "FunderBlu Marketing",
  "Campaign scope at launch."),
 ("CRM & Communications",
  "Should segments be able to exclude traders with open risk cases from campaigns? Recommended: yes, by default.",
  "FunderBlu Risk Owner",
  "Risk policy (raised with the Risk Owner). PRD recommends yes-by-default — the docs/20 segment model supports the exclusion."),
 ("CRM & Communications",
  "Who writes and owns the marketing copy for sequences and campaigns?",
  "FunderBlu Marketing",
  "Content ownership."),
 ("CRM & Communications",
  "Do we need explicit marketing consent capture at registration for EU traders in V1, or is consent implied by terms acceptance?",
  "FunderBlu Legal",
  "GDPR consent question — Legal owns it."),
 ("CRM & Communications",
  "Does FunderBlu run an active Discord community today, and is role automation worth P2 effort?",
  "FunderBlu Marketing",
  "Community-ops fact + effort judgment."),

 # ---------------- Audit & Compliance ----------------
 ("Audit & Compliance",
  "What retention period applies per audit category, for example seven years for financial actions and two years for security events?",
  "FunderBlu Legal",
  "Retention schedule — jurisdiction-driven."),
 ("Audit & Compliance",
  "Which actions trigger real-time alerts in V1: payout above threshold, production rule change, bulk suspension, or others?",
  "FunderBlu Risk Owner",
  "Alert policy (the AUD CRITICAL set exists, docs/05; the business list + thresholds are risk's)."),
 ("Audit & Compliance",
  "Can traders view audit entries about themselves in V1? Recommended: no, data subject export on request only.",
  "FunderBlu Legal",
  "GDPR posture. PRD recommends no + DSR export on request — matches the docs/05 access model."),
 ("Audit & Compliance",
  "Does hash chaining ship in V1 or later? Recommended: later, since append-only storage plus restricted database access is sufficient for V1.",
  INT,
  "Proposed — pending sign-off: adopt 'later' — V1 = append-only + restricted DB access; the hash-chain columns are already reserved for V2 (docs/05: `prev_entry_hash` — V2 hash chain)."),
 ("Audit & Compliance",
  "Which roles may access the audit viewer: admin only, or also risk and finance?",
  "FunderBlu Ops Owner",
  "Access policy (roles.yaml change + the quarterly review G39 covers it)."),
 ("Audit & Compliance",
  "What is the policy for KYC documents after account closure: anonymize, delete, or retain for the full financial retention period?",
  "FunderBlu Legal",
  "PII end-of-life policy (twin of the KYC-termination row — one answer for both)."),

 # ---------------- Platform Console ----------------
 ("Platform Console",
  "Confirm console hosting on a separate subdomain with its own auth realm, isolated from tenant identity tables.",
  INT,
  "Proposed — pending sign-off: confirm — already binding (docs/02 §7.1 realm isolation; docs/21 console routes deny non-platform sessions structurally; `con.platform_role_required`)."),
 ("Platform Console",
  "Who holds super admin seats at launch, by name, and what is the break-glass procedure if one is compromised?",
  "FunderBlu CEO",
  "Named humans — the break-glass *procedure* is already documented (docs/06 §3.6 runbook, G39: two IAM_OWNER holders, sealed credential, rotate on use); the seat-holders' names are the missing fact."),
 ("Platform Console",
  "Does tenant provisioning seed default challenge templates or start empty? Recommended: empty with an optional template library copy.",
  "FunderBlu Product Owner",
  "Onboarding UX. PRD recommends empty + optional library — the TEN-01 provisioning saga is agnostic to the seed."),
 ("Platform Console",
  "What impersonation scopes exist: read-only, full admin, or full admin excluding finance actions?",
  "FunderBlu Ops Owner",
  "Access policy (the docs/21 view-as machinery supports scopes; which ship is the policy)."),
 ("Platform Console",
  "Who is on call for platform-level alerts versus tenant- level alerts, and what thresholds separate them?",
  "FunderBlu Ops Owner",
  "On-call policy (pairs with the DevOps on-call row)."),
 ("Platform Console",
  "Does the console show tenant financial revenue by default, or only usage counts until tenant billing exists? Recommended: usage counts only.",
  "FunderBlu COO",
  "Sensitive-data visibility. PRD recommends usage-only until tenant billing exists (docs/22 V2)."),

 # ---------------- Ledger & Accounting ----------------
 ("Ledger & Accounting",
  "Confirm the V1 chart of accounts with the external accountant: are the seven accounts sufficient?",
  "FunderBlu COO",
  "Accountant confirmation — the COO's office owns the external relationship."),
 ("Ledger & Accounting",
  "Revenue recognition: recognize challenge fees at capture or defer until challenge completion? This needs an accountant ruling, not an engineering guess.",
  "FunderBlu COO",
  "The question says it — an accountant ruling, not an engineering guess."),
 ("Ledger & Accounting",
  "What settlement report format and availability does each provider offer: Match2Pay, Interkasa, and the crypto rail, CSV, API, or manual statement?",
  "External vendors (Veriff / payment rails)",
  "Provider fact — determines the nightly reconciliation input format (docs/12 §3.5)."),
 ("Ledger & Accounting",
  "At what rate do we book crypto payments and payouts: capture-time rate recorded as metadata?",
  "FunderBlu COO",
  "Accounting treatment (capture-time rate as metadata is the proposed treatment — COO/accountant confirm)."),
 ("Ledger & Accounting",
  "Who may post adjustments: COO only, or a finance role with dual control above a threshold?",
  "FunderBlu COO",
  "Money-control policy (the adjustment mechanism + dual-control template exist, docs/05/21)."),
 ("Ledger & Accounting",
  "Do ledger entries carry product and challenge tags in V1 for per-product revenue breakdown? Recommended: yes.",
  INT,
  "Proposed — pending sign-off: yes — via the existing `journal_entry.ref_type`/`ref_id` (docs/32) — the challenge/product resolves through the reference; no new columns needed."),
 ("Ledger & Accounting",
  "Confirm reporting currency and fiscal year for exports: USD and calendar year?",
  "FunderBlu COO",
  "Accounting convention confirmation."),

 # ---------------- Website / CMS ----------------
 ("Website / CMS",
  "What trigger justifies starting this module: a named tenant demand, a revenue threshold, or a sales commitment?",
  "FunderBlu CEO",
  "Strategic build-trigger (the module is V2 — docs/01 phase 3; the trigger decides WHEN)."),
 ("Website / CMS",
  "First iteration scope: templates plus pricing widget only, or include blog from the start? Recommended: templates and widget only.",
  "FunderBlu Product Owner",
  "Scope call. PRD recommends templates + widget only."),
 ("Website / CMS",
  "Does a hosted tenant site replace the tenant's existing website or coexist with it, for example platform hosts landing and pricing while the tenant keeps an external blog?",
  "FunderBlu Product Owner",
  "Product model (coexist is the likely answer — it changes little engineering)."),
 ("Website / CMS",
  "Hosting model on our stack: Nginx vhosts per tenant on Hetzner, or edge-rendered static pages?",
  INT,
  "Proposed — pending sign-off: Nginx vhosts on the same Hetzner stack — boring, in line with docs/06; the CMS module is V2, so the decision can land with that phase."),
 ("Website / CMS",
  "Is published content subject to an approval workflow in regulated markets, and who approves?",
  "FunderBlu Legal",
  "Regulatory content-approval question."),
 ("Website / CMS",
  "Do we offer import from WordPress or Webflow for existing tenant content, or start fresh only?",
  "FunderBlu Product Owner",
  "Scope call (import = a V2+ engineering investment)."),

 # ---------------- Competition / Gamification ----------------
 ("Competition / Gamification",
  "What is the build trigger: named tenant demand or a marketing-led campaign plan? FunderBlu's previous competition module had zero conversions, so validate demand before spending effort.",
  "FunderBlu CEO",
  "Strategic build-trigger — the zero-conversion history is the case for demand validation first."),
 ("Competition / Gamification",
  "Do competition accounts use a separate demo group at the broker or reuse evaluation accounts, and does the broker support the needed group?",
  "Broker (Shadab)",
  "Broker capability question (group support) + the mapping decision."),
 ("Competition / Gamification",
  "Which scoring criteria ship in the first iteration: profit percent only, or also ROI and risk-adjusted score?",
  "FunderBlu Product Owner",
  "Product scope (the scoring engine is agnostic — docs/24)."),
 ("Competition / Gamification",
  "Which prize types launch first: account credit, coupon, or cash payout, and which budget funds the prize pool?",
  "FunderBlu COO",
  "Budget + prize policy (cash prizes = payout-engine coupling)."),
 ("Competition / Gamification",
  "Is the leaderboard alias-only by default with opt-in real names, and what does legal say about public performance data?",
  "FunderBlu Legal",
  "Public-performance-data question — Legal owns it (alias-only is the safe default)."),
 ("Competition / Gamification",
  "What leaderboard update frequency is acceptable at launch: batch per sync cycle or near real-time? Recommended: batch per sync.",
  INT,
  "Proposed — pending sign-off: batch per sync cycle — the docs/24 design reads the same ANA read models; near-real-time would be a separate stream consumer."),
 ("Competition / Gamification",
  "Do competition results and badges become part of the trader's permanent record and certificates?",
  "FunderBlu Product Owner",
  "Product/brand decision (touches the D61 closed certificate set)."),

 # ---------------- Tenant Billing ----------------
 ("Tenant Billing",
  "Confirm the pricing model: fixed plan plus usage overage, pure module-based pricing, or hybrid? This is a commercial decision, not an engineering one.",
  "FunderBlu CEO",
  "Commercial decision — the question says it is not an engineering one."),
 ("Tenant Billing",
  "Which metering counters are billable: active traders, trading accounts, orders, API calls, or a subset?",
  "FunderBlu CEO",
  "Pricing mechanics — pairs with the pricing-model row."),
 ("Tenant Billing",
  "Billing currency and tax handling per tenant jurisdiction: who validates the rules, and do invoices need reverse- charge wording for EU tenants?",
  "FunderBlu Legal",
  "Tax compliance (reverse-charge wording is a Legal/finance question)."),
 ("Tenant Billing",
  "Dunning policy: grace period length, and does past due mean suspension or read-only mode first?",
  "FunderBlu COO",
  "Collections policy (the suspension machinery is spec'd, TEN-15; the grace/first-step is policy)."),
 ("Tenant Billing",
  "Is FunderBlu itself a billed subscription or exempt as the owner tenant, and how is that represented?",
  "FunderBlu CEO",
  "Commercial self-dealing question."),
 ("Tenant Billing",
  "Do B2B collections reuse the trader payment adapters or a separate invoicing provider such as Stripe Billing?",
  "FunderBlu COO",
  "Vendor choice for B2B invoicing (no Stripe in V1 for trader rails, docs/12 — B2B is a separate question)."),
 ("Tenant Billing",
  "Contract terms at launch: monthly only, or annual with discount?",
  "FunderBlu CEO",
  "Commercial terms."),

 # ---------------- BYO Integration SDK ----------------
 ("BYO Integration SDK",
  "Which languages get official SDKs at launch: TypeScript and Python only, or more?",
  "FunderBlu Product Owner",
  "Scope call (V2 module — docs/01 phase 3; the launch set is product's to size)."),
 ("BYO Integration SDK",
  "Sandbox data policy: synthetic data only, or masked production-shaped data? Recommended: synthetic only.",
  INT,
  "Proposed — pending sign-off: synthetic only — docs/28 PII posture (no production data in sandbox; the SDK-06 sandbox injects synthetic events)."),
 ("BYO Integration SDK",
  "Is the developer portal a separate documentation site or a section of the platform marketing site?",
  "FunderBlu Product Owner",
  "Product decision (docs hosting is the CMS/docs surface)."),
 ("BYO Integration SDK",
  "Which BYO paths get documented first based on real demand: checkout, affiliate, or KYC?",
  "Sales (unassigned)",
  "Demand signal — Sales owns it (unassigned role; the question was raised by 'Sales owner (unassigned)')."),
 ("BYO Integration SDK",
  "Is public API access included in base plans or reserved for enterprise tiers? Ties into tenant billing.",
  "FunderBlu CEO",
  "Commercial tiering decision."),
 ("BYO Integration SDK",
  "What is the support model for integrators: docs and sandbox only, or paid onboarding as professional services?",
  "FunderBlu CEO",
  "Professional-services commercial decision."),
 ("BYO Integration SDK",
  "How many days of webhook delivery history is replayable in sandbox and in production?",
  INT,
  "Proposed — pending sign-off: production replay from the 13-month event log (docs/04) — practical V1 window 7 days (the outbox trim horizon); sandbox 30 days of synthetic events. Proposed defaults, tunable at the V2 API freeze."),

 # ---------------- Advanced API / Developer Portal ----------------
 ("Advanced API / Developer Portal",
  "Is the developer portal public before we have external tenants? Recommended: private beta docs for design partners, public at the second tenant.",
  "Sales (unassigned)",
  "Demand/timing call (raised with 'Sales owner (unassigned)')."),
 ("Advanced API / Developer Portal",
  "Do we monetize API access separately from plans with per-call pricing, or include quotas in tiers only? Ties into tenant billing.",
  "FunderBlu CEO",
  "Commercial decision."),
 ("Advanced API / Developer Portal",
  "Which API products ship first: read-only reports, webhooks, or account management?",
  "Sales (unassigned)",
  "Demand signal — what design partners actually need."),
 ("Advanced API / Developer Portal",
  "Does partner-delegated access ship in the first iteration, or do we start with tenant-owned keys only?",
  "FunderBlu Product Owner",
  "Scope call (tenant-owned keys is the simple start)."),
 ("Advanced API / Developer Portal",
  "Is GraphQL real demand or speculation? Recommended: defer until two tenants explicitly request it.",
  "Sales (unassigned)",
  "Demand validation. PRD recommends deferral until two tenants request it."),
 ("Advanced API / Developer Portal",
  "Who owns portal content, guides, and tutorials, and what keeps them current across releases?",
  "FunderBlu Product Owner",
  "Content ownership."),
 ("Advanced API / Developer Portal",
  "Status page: build a minimal internal one or use an external provider such as Instatus? Recommended: external provider at launch.",
  INT,
  "Proposed — pending sign-off: external provider (Instatus) at launch — ops default, fits the docs/06 D57 monitoring stack (Uptime Kuma feeds it)."),

 # ---------------- Auth & Identity ----------------
 ("Auth & Identity",
  "Is 2FA mandatory for all staff roles in V1, or only finance and risk roles?",
  "FunderBlu Ops Owner",
  "Staff security policy (the spec already forces MFA on the platform org, docs/02/06 — the per-role breadth is Ops' call)."),
 ("Auth & Identity",
  "Do we ship Google OAuth in V1 or defer all social login?",
  "FunderBlu Product Owner",
  "Scope call (ZITADEL supports it, ADR-13 — shipping it is a config + support-surface decision)."),
 ("Auth & Identity",
  "What are the access token and refresh token lifetimes and rotation rules?",
  INT,
  "Proposed — pending sign-off: 15-min access token (binding — docs/02/43: the 15-min access token bounds IdP-sync exposure); session expiry idle > 30 min / absolute 24 h (docs/02 §5); refresh rotation with reuse detection (`auth.session_revoked`, docs/02)."),
 ("Auth & Identity",
  "Do migrated TTS traders get a forced password reset at cutover or a reset-email flow?",
  "FunderBlu Ops Owner",
  "Cutover procedure decision (migration runbook, docs/25)."),
 ("Auth & Identity",
  "Does any V1 tenant require SSO or SAML, which would pull it into V1 scope?",
  "FunderBlu COO",
  "Commercial fact — 'does any V1 tenant require X' is a sales/COO fact, not an engineering guess (ZITADEL ships SSO/SAML, ADR-13 — enabling it is a config + SCIM scope question)."),
 ("Auth & Identity",
  "Do we allow super admin impersonation of tenant admins for support, and under what audit rules?",
  "FunderBlu Ops Owner",
  "Access policy (the view-as machinery + deny-list exist, docs/21; the allow + audit rules are Ops')."),

 # ---------------- Event Bus & Webhooks ----------------
 ("Event Bus & Webhooks",
  "Do outbound tenant webhooks ship in V1 or immediately after MVP , given FunderBlu does not need them?",
  "FunderBlu CEO",
  "Scope call. Note: the platform SHIPS Hook0 in V1 (docs/01 §1.1 deployable; EVT-10/signed delivery) — the question is whether FunderBlu *uses* it at launch; the build-vs-use distinction is CEO's."),
 ("Event Bus & Webhooks",
  "Redis Streams retention: what max stream length and retention window do we configure for V1?",
  INT,
  "Proposed — pending sign-off: per the docs/04 §11 parameters — MAXLEN ~100k per stream (approximate trim, keeps XADD O(1)); streams are transport only, rebuildable from the 13-month `events` log (docs/04 §5.4)."),
 ("Event Bus & Webhooks",
  "Event log retention period for replay: 90 days, 1 year, or permanent archive to object storage?",
  INT,
  "Proposed — pending sign-off: 13 months in PG, then archive to R2 — already binding (docs/04: 'retention: V1 keep 13 months, then archive to R2 (EVT-22)')."),
 ("Event Bus & Webhooks",
  "Who approves event schema changes and version bumps to prevent contract drift between modules?",
  INT,
  "Proposed — pending sign-off: module owner proposes, contract gates enforce — ADR-7 additive-only versioning (bump `version` on payload change; unknown-higher → DLQ + alert), enforced by the docs/99 0.10 contract checks (catalog + schema + payload gates). A schema change is a PR against `contracts/` reviewed by the module owner + BE lead."),
 ("Event Bus & Webhooks",
  "Is the outbox relay a separate process or a background worker inside the API binary for V1? Recommended: separate process.",
  INT,
  "Proposed — pending sign-off: separate process — binding (docs/01 §1.1 `relay` deployable; the failover story is docs/06 §3.7 / D76)."),
 ("Event Bus & Webhooks",
  "Do any V1 flows require stronger than at-least-once delivery plus idempotent consumers? Expected answer is no.",
  INT,
  "Proposed — pending sign-off: none — at-least-once + idempotent consumers IS the binding semantics (ADR-6/7, docs/04 §4.3); no V1 flow needs exactly-once at the bus level (money paths are guarded by idempotency keys + state machines instead)."),

 # ---------------- API Gateway ----------------
 ("API Gateway",
  "What are the default rate limits per route group for trader, admin, and webhook traffic?",
  INT,
  "Proposed — pending sign-off: the binding table (docs/55 §4.6) — per-user 100 rpm (tenant-plan adjustable), auth 10 / 5 min, payout 5 / h, Cloudflare per-IP edge limit outside; inbound provider webhooks are handler-deduped by provider event id (no app rate limit)."),
 ("API Gateway",
  "Do per-tenant quotas ship in V1 or only after the second paying tenant? Expected: after.",
  "FunderBlu CEO",
  "Commercial trigger (the quota machinery GW-29 exists; WHEN it ships is a business call)."),
 ("API Gateway",
  "Versioning strategy: URL versioning only, or also header-based negotiation? Recommended: URL only.",
  INT,
  "Proposed — pending sign-off: URL only — the spec is built on /v1/... with Deprecation/Sunset headers (docs/55 GW-28; docs/04 §4.2 envelope)."),
 ("API Gateway",
  "Do we expose a public tenant API in V1 or only inbound and outbound webhooks? Ties to the EVT-11 question.",
  "FunderBlu CEO",
  "Scope call. Spec posture: the public tenant API is V2 (docs/01 phase 3; EVT-11) — V1 = inbound provider webhooks + outbound tenant webhooks only."),
 ("API Gateway",
  "Who defines and reviews the PII exclusion list for request logs?",
  "FunderBlu Legal",
  "PII policy (the redaction machinery exists, docs/04/28; the list is Legal's)."),

 # ---------------- Tenant Management ----------------
 ("Tenant Management",
  "Custom domain SSL in V1: manual via Cloudflare for SaaS, or automated certificate provisioning?",
  INT,
  "Proposed — pending sign-off: V1 is subdomain-only ({slug}.alpha1.io, docs/03); custom domain is the V1.1 provisioning step (docs/03 §3 step 5) with manual Cloudflare-for-SaaS at that point; automated certificate provisioning is a V2 item (TEN-05)."),
 ("Tenant Management",
  "Who may edit the terminology map: tenant admin or super admin only?",
  "FunderBlu Product Owner",
  "Brand-control decision (the terminology map mechanism is TEN-32 V2 — the answer decides its scope too)."),
 ("Tenant Management",
  "Impersonation consent model: in-product consent per session or contract-level permission?",
  "FunderBlu Product Owner",
  "Product/UX policy (the docs/21 view-as machinery supports both)."),
 ("Tenant Management",
  "What happens to existing data when a module entitlement is disabled, for example affiliate commissions after affiliate is turned off?",
  "FunderBlu Product Owner",
  "Product semantics — disable = hide the surface, keep the data (the TEN-09 entitlement lifecycle exists; the data policy is product's)."),
 ("Tenant Management",
  "Do we support multiple brands or sub-tenants under one firm in V1? Expected answer is no.",
  "FunderBlu CEO",
  "Scope call. Spec posture: one firm = one tenant (docs/47 multi-tenancy model); sub-tenants are a structural V2+ question."),
]

out = {
    "version": 1,
    "generated": "2026-09-20",
    "source": "scripts/prd-workbook.json (docs/37 open rows), triaged in the 2026-09-20 gap-closure pass",
    "buckets": BUCKETS,
    "internal_bucket": INT,
    "note": ("Every docs/37 open PRD question is assigned to the stakeholder who can answer it. "
             "Rows in the internal bucket carry a proposed answer marked 'Proposed — pending sign-off'; "
             "proposals adopt the PRD's own 'Recommended:' text where present, or the binding spec where it "
             "already decided the point. NO row is marked answered — sign-off is the owner's to give "
             "(the D-number convention: an answer lands only with a real owner decision)."),
    "rows": [
        {"section": s, "q": q, "bucket": b, "note": n} for (s, q, b, n) in ROWS
    ],
}
assert len(ROWS) == 197, f"expected 197 triage rows, got {len(ROWS)}"
p = ROOT / "prd-question-triage.json"
p.write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"wrote {p.name}: {len(ROWS)} rows, buckets:")
from collections import Counter
for b, n in Counter(r[2] for r in ROWS).most_common():
    print(f"  {n:3d}  {b}")
